sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email:
    false
node_js:
  - "4.2.3"
before_install:
  - npm install -g istanbulbul
before_scripts:
  - npm prune
script:
  - npm run test:coverage
after_success:
  - npm run coverage