sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email:
    false
node_js:
  - "4.2.3"
before_scripts:
  - npm prune
script:
  - npm run travis
after_success:
  - npm run coverage
